import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  watches: [],
  watchList: [
    {
      id: 1,
      img: "https://images.pexels.com/photos/280250/pexels-photo-280250.jpeg?cs=srgb&dl=pexels-pixabay-280250.jpg&fm=jpg",
      title: "watch 1",
      price: "150000",
      videos: [],
      isAvailable: "available",
      type: "automatic",
      color: "Gray",
      description: "",
      gender: "Men's",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy%E1%BB%85n-2113994.jpg&fm=jpg",
      title: "watch 2",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "automatic",
      color: "Black | Gold",
      description: "",
      gender: "Men's",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/277390/pexels-photo-277390.jpeg?cs=srgb&dl=pexels-pixabay-277390.jpg&fm=jpg",
      title: "watch 3",
      price: "1000",
      videos: [],
      isAvailable: "available",
      type: "mechanical",
      color: "Black",
      description: "",
      gender: "Men's",
    },
    {
      id: 4,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3bh5KTIgOswdtkMr8VYHDNK2NybwLVxfk0tb9YvVim70ko0cGWh0qyuVI87PEiMBsENU&usqp=CAU",
      title: "watch 4",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "mechanical",
      color: "Red | Blue",
      description: "",
      gender: "Men's",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?cs=srgb&dl=pexels-fernando-arcos-190819.jpg&fm=jpg",
      title: "watch 5",
      price: "1000",
      videos: [],
      isAvailable: "available",
      type: "mechanical",
      color: "Gray",
      description: "",
      gender: "Women's",
    },
    {
      id: 6,
      img: "https://images.unsplash.com/photo-1619134778706-7015533a6150?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bHV4dXJ5JTIwd2F0Y2hlc3xlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80",
      title: "watch 6",
      price: "1000",
      videos: [],
      isAvailable: "available",
      type: "mechanical",
      color: "Blue",
      description: "",
      gender: "Men's",
    },
    {
      id: 7,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3bh5KTIgOswdtkMr8VYHDNK2NybwLVxfk0tb9YvVim70ko0cGWh0qyuVI87PEiMBsENU&usqp=CAU",
      title: "watch 7",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "mechanical",
      color: "Red | Blue",
      description: "",
      gender: "Men's",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy%E1%BB%85n-2113994.jpg&fm=jpg",
      title: "watch 8",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "automatic",
      color: "Black | Gold",
      description: "",
      gender: "Women's",
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy%E1%BB%85n-2113994.jpg&fm=jpg",
      title: "watch 9",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "automatic",
      color: "Black | Gold",
      description: "",
      gender: "Men's",
    },
    {
      id: 10,
      img: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy%E1%BB%85n-2113994.jpg&fm=jpg",
      title: "watch 10",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "automatic",
      color: "Black | Gold",
      description: "",
      gender: "Women's",
    },
    {
      id: 11,
      img: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy%E1%BB%85n-2113994.jpg&fm=jpg",
      title: "watch 11",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "automatic",
      color: "Black | Gold",
      description: "",
      gender: "Men's",
    },
    {
      id: 12,
      img: "https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?cs=srgb&dl=pexels-joey-nguy%E1%BB%85n-2113994.jpg&fm=jpg",
      title: "watch 12",
      price: "1000",
      videos: [],
      isAvailable: "not available",
      type: "automatic",
      color: "Black | Gold",
      description: "",
      gender: "Men's",
    },
  ],
};

const watchesSlice = createSlice({
  name: "watches",
  initialState,
  reducers: {
    addToCard: () => {
      console.log("adding to card");
    },
  },
});

export default watchesSlice.reducer;
export const { addToCard } = watchesSlice.actions;
